//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement_Web_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEvent()
        {
            this.tblUserEvents = new HashSet<tblUserEvent>();
        }
    
        public int Event_ID { get; set; }
        public string Event_Name { get; set; }
        public string Event_Description { get; set; }
        public int Event_Category_Id { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public string Event_Location { get; set; }
        public string Allow_Registration { get; set; }
        public string Event_Logo { get; set; }
        public string Event_Image { get; set; }
        public decimal AdultticketPrize { get; set; }
        public decimal ChildticketPrize { get; set; }
    
        public virtual tblEventCategory tblEventCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserEvent> tblUserEvents { get; set; }
    }
}
