//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement_Web_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserEvent
    {
        public int ID { get; set; }
        public string User_Id { get; set; }
        public int Event_Id { get; set; }
        public int Children_number { get; set; }
        public int Adult_number { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual tblEvent tblEvent { get; set; }
    }
}
